/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: corenova.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

//#include "corenova.pb-c.h"
void   rpc__request__init
                     (Rpc__Request         *message)
{
  static Rpc__Request init_value = RPC__REQUEST__INIT;
  *message = init_value;
}
size_t rpc__request__get_packed_size
                     (const Rpc__Request *message)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__request__pack
                     (const Rpc__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__request__pack_to_buffer
                     (const Rpc__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Request *
       rpc__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Request *)
     protobuf_c_message_unpack (&rpc__request__descriptor,
                                allocator, len, data);
}
void   rpc__request__free_unpacked
                     (Rpc__Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__response__init
                     (Rpc__Response         *message)
{
  static Rpc__Response init_value = RPC__RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__response__get_packed_size
                     (const Rpc__Response *message)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__response__pack
                     (const Rpc__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__response__pack_to_buffer
                     (const Rpc__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Response *
       rpc__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Response *)
     protobuf_c_message_unpack (&rpc__response__descriptor,
                                allocator, len, data);
}
void   rpc__response__free_unpacked
                     (Rpc__Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char rpc__request__magic__default_value[] = "CENA";
static const ProtobufCFieldDescriptor rpc__request__field_descriptors[4] =
{
  {
    "magic",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, magic),
    NULL,
    &rpc__request__magic__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, from),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, to),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__request__field_indices_by_name[] = {
  3,   /* field[3] = data */
  1,   /* field[1] = from */
  0,   /* field[0] = magic */
  2,   /* field[2] = to */
};
static const ProtobufCIntRange rpc__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpc__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.request",
  "Request",
  "Rpc__Request",
  "rpc",
  sizeof(Rpc__Request),
  4,
  rpc__request__field_descriptors,
  rpc__request__field_indices_by_name,
  1,  rpc__request__number_ranges,
  (ProtobufCMessageInit) rpc__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t rpc__response__code__default_value = -1;
static const ProtobufCFieldDescriptor rpc__response__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__Response, code),
    NULL,
    &rpc__response__code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Response, format),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Rpc__Response, has_data),
    offsetof(Rpc__Response, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__response__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = data */
  1,   /* field[1] = format */
};
static const ProtobufCIntRange rpc__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.response",
  "Response",
  "Rpc__Response",
  "rpc",
  sizeof(Rpc__Response),
  3,
  rpc__response__field_descriptors,
  rpc__response__field_indices_by_name,
  1,  rpc__response__number_ranges,
  (ProtobufCMessageInit) rpc__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
